[package]
name = "ariel-os-wireguard-example"
version = "0.1.0"
edition = "2024"

[dependencies]
ariel-os = { path = "build/imports/ariel-os/src/ariel-os", features = [
  "csprng",
  "dns",
  "hwrng",
  "net",
  "random",
  "tcp",
] }
ariel-os-boards = { path = "build/imports/ariel-os/src/ariel-os-boards" }
data-encoding-macro = "0.1.18"
der = { version = "0.8", default-features = false, features = ["heapless"] }
embassy-executor = "0.9.1"
embassy-wireguard = { path = "../ariel-os-wireguard", features = ["defmt"] }
rand_core = "0.9.3"
reqwless = { version = "0.14.0", default-features = true, features = [
  "defmt",
  "embedded-tls",
] }

[patch.crates-io]
#boringtun
ip_network = { git = "https://github.com/SimonIT/ip_network.git", branch = "no_std" }
ip_network_table = { git = "https://github.com/SimonIT/ip_network_table.git", branch = "no_std" }
ip_network_table-deps-treebitmap = { git = "https://github.com/SimonIT/treebitmap.git", branch = "fix-alloc" }
ring = { git = "https://github.com/SimonIT/ring.git", branch = "ariel-os" }

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s"     # Optimize for size even in debug builds

[profile.release]
incremental = false
codegen-units = 1
debug = true        # Required for defmt
lto = false
opt-level = "s"

[profile.release.package.esp-wifi]
opt-level = 3
